apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag-aug26-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag-aug26-1:4fdc460c877c8e5e7ae4fe892e57e5367e4c63fa@sha256:e603eec8425185c138d80dec7e83a65a61d29b0d889f2dded6e0f30d70887f5c # use pre-built to bootstrap 
          name: app-inference
